server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://gestion_pedidos_db:5432/gestion_pedidos
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true